version: "3.9"

services:
  app:
    container_name: e-catalog-migas
    build: .
    ports:
      - "3310:80"
    restart: unless-stopped
    networks:
      - public_net

networks:
  public_net:
    external: true
